### ISSUE TITLE
Can't compile in Debian 9.8

### ISSUE THREAD

**Issue by negora** [lanmessenger/lanmessenger#17]
I'm trying to compile the project with Debian 9.8, but I'm getting some errors. I'm using QT 5.7.1, which is the version bundled with this version of Debian.

I've needed to install the following packages, which were missing in my installation:

```bash
apt-get install \
		libssl-dev \
		qtmultimedia5-dev
```

Then, I've followed these steps to compile `lmcapp`:

```bash
cd lmcapp/src/
qmake
make
```

The process has finished successfully.

Then, I've tried to do the same with `lmc`:

```bash
cd lmc/src/
qmake
make
```

But it has shown multiple errors. I've attached the full log to this ticket. Some of the errors are these:

> crypto.cpp:76:17: error: aggregate ‘EVP_CIPHER_CTX ectx’ has incomplete type and cannot be defined
>  EVP_CIPHER_CTX ectx, dctx;
>                 ^~~~~~~~~~~~
> ...
>
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h: In member function ‘const T QMap<K, V>::value(const Key&, const T&) const [with Key = QString; T = evp_cipher_ctx_st]’:
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:388:59: error: invalid use of incomplete type ‘struct evp_cipher_ctx_st’
>     const T value(const Key &key, const T &defaultValue = T()) const;

Thank you.
[error.log](https://github.com/lanmessenger/lanmessenger/files/2919397/error.log)

**Comment by marzoul** [comment]
This should be addressed by my pull request https://github.com/lanmessenger/lanmessenger/pull/18
A bit of testing is needed though, because the main application still does not show on my system but probably not related to OpenSSL version.
Please test.

**Comment by lanmessenger** [comment]
@marzoul, @negora , I merged commit.

**Comment by negora** [comment]
@marzoul, @lanmessenger: Thank you. I've downloaded the last version of the GIT repository and now I've been able to compile `lmc` succesfully ;) .

After doing so, I've had to edit the `lmc/src/scripts/buildx11` file so that it points to the proper QT library directory and to the SSL libraries of the system:

```diff
--- scripts/buildx11-20190304-135700.bak	2019-03-04 13:44:26.760631492 +0100
+++ scripts/buildx11	2019-03-04 14:21:08.997433066 +0100
@@ -1,4 +1,8 @@
 #!/bin/sh
+
+LIBDIR='/usr/lib/x86_64-linux-gnu'
+QTDIR="$LIBDIR/qt5"
+
 set -e
 
 if [ "$1" = "" ]; then
@@ -47,8 +51,8 @@
 
 echo "Copying libraries..."
 cp -v ../../lmcapp/lib/liblmcapp.so.2 $1
-cp -v -f ../../openssl/lib/libcrypto.so.1.0.0 $1
-cp -v -f ../../openssl/lib/libssl.so.1.0.0 $1
+cp -v -f "$LIBDIR/libcrypto.so.1.1" $1
+cp -v -f "$LIBDIR/libssl.so.1.1" $1
 echo "Done."
 
 echo "Copying launch scripts..."

```

Then, I've run such script, using `/usr/local/lib/lan-messenger/` as the destination directory. But I've had to manually copy the `lmc/releases/lan-messenger` binary to the destination because it hasn't been copied automatically (`lan-messenger.sh` has complained about it).

Unfortunately, when I've run `lan-messenger.sh`, I've got this error:

```
../crypto/evp/evp_enc.c:156: OpenSSL internal error: assertion failed: ctx->cipher->block_size == 1 || ctx->cipher->block_size == 8 || ctx->cipher->block_size == 16
/usr/local/lib/lan-messenger/lan-messenger.sh: line 15: 13042 Aborted                 $dirname/$appname "$@"

```

**Comment by marzoul** [comment]
@negora @lanmessenger : thank you for the report. This openssl error is puzzling.

On my side I also can't rely on buildx11 script as-is because of many hardcoded versions and paths, plus unknown command lrelease.
So I've tried the standard way of building QT applications :
`qmake-qt5`
`make`

This has the advantage of using the system libraries for openssl and QT, in the hope that it's not needed to copy these to final install path (which is system path as I'm building an Archlinux package).
But for compilation I need a manual edit of the qmake-generated Makefile because of an include of system header strings.h. I mentioned this for https://github.com/lanmessenger/lanmessenger/issues/11.
Unfortunately, the application does not show, seems to run, no message is printed... I don't really know what to do. Silent errors are difficult to address.

**Comment by negora** [comment]
@marzoul @lanmessenger

I only program in Java and TypeScript, so I've not much idea about C, C++ and QT. But this is what I did to compile the application in Debian 9.8, following the instructions from the `*.md` files:

```bash
# These packages were missing from my install, so I had
# to install them.
apt-get install \
		libssl-dev \
		qtmultimedia5-dev
		
cd lanmessenger-master/

# To compile "lmcapp", I did this.
# Note: I used "qmake" instead of "qmake-qt5" because it
# already belongs to version 5 ("qmake-qt5" doesn't exist
# in Debian).
cd lmcapp/src/
qmake
make

# To compile "lmc".
cd ../../lmc/src/
qmake
make

# Then, I had to manually edit the "buildx11" file with the changes 
# that I mentioned before.
vim scripts/buildx11

# Finally, I run "buildx11" to construct the installation
# directory (with sound files, translations, etc.)
mkdir /usr/local/lib/lan-messenger/
./scripts/buildx11 /usr/local/lib/lan-messenger/

# The main binary file wasn't copied to the destination, though.
# So I had to copy it by myself.
cp --archive ../release/lan-messenger /usr/local/lib/lan-messenger/
```

**Comment by marzoul** [comment]
@negora @lanmessenger I don't use the buildx11 script for install. This is evil. Instead I use it to construct a temporary installation directory that I archive as an Archlinux package and then I install this package.

But installed or not, run from build directory or from system /usr/ installed location, no difference. No application GUI shows, even though there is no error message. I don't even know what lan-messenger GUI looks like xD

Maybe something gets stalled and I don't get as far as @negora to hit an openssl error... Or it just works on my system except for the GUI... I'll have to try compilation in debug mode, in the hope something gets visible...
